# Generated by Django 4.2.6 on 2023-10-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_department', models.CharField(max_length=50)),
                ('employee_role', models.CharField(max_length=50)),
                ('employee_date_started_in_each_role', models.CharField(max_length=50)),
                ('employee_date_left_role', models.CharField(max_length=50)),
                ('employee_duties_ine_each_role', models.CharField(max_length=50)),
            ],
        ),
    ]
