# Generated by Django 4.2.6 on 2023-10-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_date_left_role',
            new_name='employee_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_date_started_in_each_role',
            new_name='employee_duties',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_duties_ine_each_role',
        ),
    ]
