# Generated by Django 4.2.6 on 2023-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_employee_employee_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_date_left_role',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_date_started_in_each_role',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
