# Generated by Django 4.2.6 on 2023-10-11 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_remove_employee_employee_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_date_left_role',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_date_started_in_each_role',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
