# Generated by Django 4.2.6 on 2023-10-11 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_employee_employee_date_left_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_date_left_role',
            field=models.DateField(verbose_name=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_date_started_in_each_role',
            field=models.DateField(verbose_name=datetime.datetime),
        ),
    ]
