# Generated by Django 4.2.6 on 2023-10-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_employee_employee_date_left_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_date_left_role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_date_started_in_each_role',
        ),
    ]
